### ISSUE TITLE
possible merge with HEALPix.jl

### ISSUE THREAD

**Issue by mweastwood** [ziotom78/Healpix.jl#1]
I've just found this repository and I feel the need to reach out because I'm the author of [HEALPix.jl](https://github.com/mweastwood/HEALPix.jl), which I want to register as a Julia package. However, it would be nice to avoid the confusion and duplication of effort associated with having 2 HEALPix packages.

My package is a straight wrapper of `libchealpix` and some of the C++ routines (specifically `alm2map` and `map2alm`, which was my motivation for creating this package in the first place). On the other hand, your package has nice Julia implementations of some of these functions. I think a good plan for a merged package would export the Julia implementation of a function (when it exists), however it could be tested against the official library implementation.

We would also need to decide on whether to use GPL (my preference) or BSD as a license.

Let me know if you have any thoughts on this potential merge.

**Comment by ziotom78** [comment]
Hi Michael,

 Neither I was aware of your library. My objective is to have a 100% Julia 
library which does not depend on libchealpix (unlike e.g. Healpy). This 
would allow to use the library under Windows too. (Libchealpix is not 
supported on this platform, and even if it should be theoretically possible 
to make it compiled, I think the result would be too cumbersome to use and 
maintain.)

Even if am a Linux user, I find Windows quite important to support: many of 
my coworkers use it, and if Healpix in Julia is their only choice for 
analysing CMB maps, I hope this will be enough motivation for them to try 
Julia! (A big plus is that by writing so many Healpix functions in Julia 
I'll learn a lot about it!)

I am not opposed against the idea of joining our efforts, but the objective 
of having a library that does not require to compile Libchealpix is a 
strong requirement for me. But I understand your idea of just binding 
Libchealpix: in this way, Julia would have a working Healpix package in a 
short time!

I see two ways to go:
1. We follow your idea, but we make the use of the C bindings optional. Or, 
better, we find a reasonable way to make the package ready to install under 
Windows too).
2. We keep our libraries separated, but with different names so that their 
difference is clear. For instance, Chealpix.jl vs Julia-healpix.

Tell me what you think,
 Maurizio.



Inviato con AquaMail per Android
http://www.aqua-mail.com


Il 17 agosto 2015 20:17:36 Michael Eastwood <notifications@github.com> ha 
scritto:

**Comment by mweastwood** [comment]
Apologies for the delay in replying. I've decided that I am going to rename my package to LibHealpix.jl to represent that it is only meant to be a wrapper of the C and C++ libraries. I think that is the easiest way forward for now.

**Comment by ziotom78** [comment]
Ok, I agree. Many thanks for your efforts, since it will take some time for my library to be reasonably complete, I'll sure use yours in the months to come!
